### ISSUE TITLE
Vite not working on localhost

### ISSUE THREAD

**Issue by zawilliams** [lancastersoftwareco/laravel-template#2]
I've set things up and ran `sail up` and can view the Laravel install from `localhost`, but when I run `npm run dev` and open `localhost:3000` I am getting "This localhost page can’t be found".

Once I've cloned the repo I...

1. `cd` into the directory
2. Run the `docker run` command
3. Copy the `.env.example` to `.env`
4. Run `sail up`
5. Run `npm install`
6. Run `npm run dev`

Am I missing any steps to get this up and running correctly?

**Comment by nathanheffley** [comment]
`localhost:3000` is where your Vite assets will be served from, if you visit just `localhost` I believe it should load. Let me know if it doesn't!

**Comment by nathanheffley** [comment]
Sorry, I just re-read your ticket, and to clarify, you should be able to visit just `localhost` to where your Laravel project is working, and it should hotload the Vite assets from `localhost:3000`. I am not 100% sure how the dev server works, and it only seems to start serving assets after you open the Laravel project. Just visiting the Vite server directly doesn't seem to trigger an initial load of the assets.

**Comment by zawilliams** [comment]
Ahhh, ok. I completely misunderstood how it was working. You're right. I'm used to running Laravel Mix and running BrowserSync and it proxying to `localhost` but serving from `localhost:3000`.

Thanks for the clarification @nathanheffley - I confirmed it does work the way you're describing.
